version: '3.3'
services:
###########
# Php #
###########  
  php:
    build: ./php7-fpm
    container_name: php
    environment:
        APP_ENV: dev
    volumes:
      - ./app/:/var/www/app/
    networks:
      - elk  
###########
# Nginx #
###########      
  nginx:
    build: ./nginx
    container_name: web
    volumes:
      - ./app/:/var/www/app/
      - ./nginx/log:/var/log/nginx  
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=elk"
      - "traefik.http.routers.nginx.rule=Host(`www.symfony-4-docker-dev.com`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=81"
    ports:
      - 81:81
    networks:
      - elk  
################
# Elasticsearch #
################      
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
        PASSWORD_ELK: $PASSWORD_ELK
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=elk"
      - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.com`)"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"    
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
###########
# Logstash #
###########       
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
        PASSWORD_ELK: $PASSWORD_ELK
    container_name: logstash    
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    expose: 
      - "5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
###########
# Kibana #
###########        
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
        PASSWORD_ELK: $PASSWORD_ELK
    container_name: kibana        
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=elk"
      - "traefik.http.routers.kibana.rule=Host(`kibana.com`)"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"          
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch  
###########
# filebeat #
###########        
  filebeat:
    build: ./filebeat
   
    container_name: filebeat
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./filebeat/config/nginx.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/log:/var/log/nginx
    networks:
      - elk
    depends_on: 
      - php
      - nginx      
      - logstash
      - elasticsearch
      - kibana
    links: 
      - logstash         
###########
# Traefik #
###########
  traefik:
    image: traefik:v2.1
    container_name: traefik    
    command: 
      - --api.insecure=true 
      - --providers.docker 
      - --providers.docker.exposedByDefault=false 
      - --providers.docker.network=internal
    ports:
      - "80:80"
      - 8080:8080
    networks:
      - elk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      
###########
# Portainer #
###########        
  portainer:
      image: portainer/portainer
      container_name: portainer
      expose:
        - "9000"
      networks:
        - elk
      labels:    
      - "traefik.enable=true"
      - "traefik.docker.network=elk"
      - "traefik.http.routers.portainer.rule=Host(`portainer.com`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" 
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - portainer-data:/data

networks:
  elk:
    driver: bridge
volumes:
  elasticsearch:
  portainer-data: